MeuProjeto/urls.py
# Arquivo: MeuProjeto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import apps.users.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('apps.users.urls', namespace="users")),
]

apps/users/urls.py
# Arquivo: apps/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/$', views.RegistrationView.as_view(), name="register"),
    url(r'^playlist-tracks/(?P<playlist_id>\w{0,50})', views.playlisttracks, name="playlist-tracks"),
    url(r'^search/$', views.searchtrack, name="search"),
    url(r'^add-favorite-track/$', views.add_new_favorite_track, name='add_new_favorite_track'),
]

apps/users/models.py
# Arquivo: /apps/users/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext as _
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin


class EmailUserManager(BaseUserManager):
    def create_user(self, *args, **kwargs):
        email = kwargs["email"]
        email = self.normalize_email(email)
        password = kwargs["password"]
        kwargs.pop("password")

        if not email:
            raise ValueError(_('USUÁRIOS DEVEM TER OBRIGATORIAMENTE UM ENDEREÇO DE EMAIL!'))

        user = self.model(**kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, *args, **kwargs):
        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.save(using=self._db)
        return user


class MyUser(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(
        verbose_name=_('Email'),
        unique=True,
	help_text=_('<------------------------------------------------------'),
    )
    first_name = models.CharField(
        verbose_name=_('Nome'),
        max_length=50,
        blank=False,
        help_text=_('Enter your name'),
    )
    last_name = models.CharField(
        verbose_name=_('Sobrenome'),
        max_length=50,
        blank=False,
        help_text=_('Enter your last name'),
    )
    spotify_username = models.CharField(
        verbose_name=_('Usuário do Spotify'),
        max_length=50,
        blank=False,
        help_text=_('Forgot? Go to: <a href ="https://www.spotify.com/us/account/overview">Spotify User</a>')
    )

    USERNAME_FIELD = 'email'
    objects = EmailUserManager()


class IdeaTrack(models.Model):
    name = models.CharField(verbose_name=_('Nome'), max_length=256)
    artist = models.CharField(verbose_name=_('Artista'), max_length=256)
    user = models.ForeignKey(MyUser)

    def __str__(self):  #For Python 2, use __str__ on Python 3
        return self.name

apps/users/forms.py
# Arquivo: apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import MyUser, IdeaTrack


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ['first_name', 'last_name', 'spotify_username', 'email']


class TrackForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Nome")
    artist = forms.CharField(max_length=128, help_text="Artista")

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = IdeaTrack
        fields = ['name', 'artist']
        exclude = ('user',)

apps/users/views.py
# Arquivo: /apps/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.http import HttpResponseRedirect
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse_lazy, reverse
from django.template.defaulttags import register


from .forms import CustomUserCreationForm, TrackForm
from .models import MyUser, IdeaTrack
import apps.users.spotipy_functions as spotipy_manager


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@register.filter
def get_playlist_id(playlist):
    print(playlist['id'])
    return playlist['id']


@register.filter
def get_artist_name(track):
    return track['artists'][0]['name']


def add_new_favorite_track(request):
    context_dict = {}
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = TrackForm(request.POST)

            # Have we been provided with a valid form?
            if form.is_valid():
                # Save the new category to the database.
                    track = form.save(commit=False)
                    track.user = request.user
                    track.save()

                # Now call the index() view.
                # The user will be shown the homepage.
                    return home(request)
            else:
                # The supplied form contained errors - just print them to the terminal.
                print(form.errors)
        else:
            # If the request was not a POST, display the form to enter details.
            form = TrackForm()

        # Bad form (or form details), no form supplied...
        # Render the form with error messages (if any).
        return render(request, 'users/add-favorite-track.html', {'form': form})


def searchtrack(request):
    result_list = []
    context_dict = {}
    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            result_list = spotipy_manager.search_tracks(query)
    context_dict['result_list'] = result_list
    context_dict['name'] = 'name'
    context_dict['id'] = 'id'

    return render(request, 'users/search.html', context_dict)


def playlisttracks(request, playlist_id):
    context_dict = {}
    context_dict['playlist_id'] = playlist_id
    if request.user.is_authenticated:
        playlist_tracks = spotipy_manager.show_playlist_tracks(request.user.spotify_username, playlist_id)
        print(playlist_tracks.__len__())
        context_dict['tracks'] = playlist_tracks
        context_dict['name'] = 'name'
        context_dict['id'] = 'id'
        context_dict['playlist_name'] = spotipy_manager.get_playlist_name(request.user.spotify_username, playlist_id)
    return render(request, 'users/playlist-tracks.html', context_dict)


def list_fav_tracks(query):
    list_fav = list()
    for e in query:
        list_fav.append(e)
    return list_fav


def home(request):
    context_dict = {}
    if request.user.is_authenticated:
        user_playlists = spotipy_manager.playlist_list(request.user.spotify_username)
        context_dict['playlists'] = user_playlists
        context_dict['name'] = 'name'
        try:
            context_dict['favorite_tracks'] = list_fav_tracks(IdeaTrack.objects.filter(user=request.user))
        except IdeaTrack.DoesNotExist:
            context_dict['favorite_tracks'] = None
    return render(request, 'users/home.html', context_dict)


def login_view(request, *args, **kwargs):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('users:home'))

    kwargs['extra_context'] = {'next': reverse('users:home')}
    kwargs['template_name'] = 'users/login.html'
    return login(request, *args, **kwargs)


def logout_view(request, *args, **kwargs):
    kwargs['next_page'] = reverse('users:login')
    return logout(request, *args, **kwargs)


class RegistrationView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = "users/register.html"

templates/users/add-favorite-track.html
<body style="background:#88FDBD">
<body><center>
<br><br>

        <h1>Adicionar Nova Música Favorita</h1>
<img src="http://www.simbolos.net.br/wp-content/uploads/2013/11/simbolo-de-musica.jpeg" height="200" width="500" border="5">
<br><br>

        <form id="favorite_track_form" method="post" action="{% url 'users:add_new_favorite_track' %}">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
<br><br>
            <input type="submit" name="submit" value="Adicionar Favorita!" />
        </form>
    </body>

templates/users/add-playlist.html
<body>
<body style="background:#88FDBD">
<br><br>
        <h1>Adicionar Nova Música Favorita</h1>

        <form id="favorite_track_form" method="post" action="{% url 'users:add_new_favorite_track' %}">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Adicionar Favorita!" />
        </form>
    </body>

templates/users/home.html
<!-- Arquivo: templates/users/home.html -->
<body style="background:#88FDBD">
<h2><center><br>SEJA BEM-VINDO(A) {% if user.is_authenticated %}{{ user.first_name }}{% else %}usuário anônimo{% endif %}</h2>
<center>

{% if user.is_authenticated %}
<h4>
<a href="{% url 'users:logout' %}">Logout (Sair)</a></h4>
    <ul>

<h3>SUAS PLAYLISTS:</h3>
<img src="http://www.coxinhanerd.com.br/wp-content/uploads/2015/04/playlist-para-curtir-o-final-de-semana.png" height="110" width="300" border="5">
<br><br>
    {% for playlist in playlists %}
        <li><a href="{% url 'users:playlist-tracks' playlist|get_item:'id' %}">{{playlist|get_item:name}}</a></li>
    {% endfor %}
</ul>
<br>
<a href="{% url 'users:add_new_favorite_track' %}"><h3>Adicionar música favorita</h3></a><br/>
{% if favorite_tracks %}
<ul>
        <h3>SUAS MÚSICAS FAVORITAS:</h3>
    {% for track in favorite_tracks %}
        <li>{{track.name}} - {{track.artist}}</li>
    {% endfor %}
</ul>
{% endif %}
{% else %}
<p><a href="{% url 'users:register' %}">Registre-se</a></p>
<p><a href="{% url 'users:login' %}">Login</a></p>
{% endif %}

templates/users/login.html
<!-- Arquivo: templates/users/login.html -->

<h1><br><br><br><center> LOGIN</h1>

<body style="background:#88FDBD">
<center>
<img src="https://myslu.slu.edu/res/images/cas-padlock-icon.png" height="150" width="150" border="5"> 

<form role="form" class="form" method="POST" action="{{ request.path }}{% if next %}?next={{ next }}{% endif %}">
{% csrf_token %}
{{ form.as_p }}

<button type="submit" class="btn btn-warning"><i class="fa fa-plus" aria-hidden="true"></i> Login</button>
</form>

templates/users/playlist-tracks.html
<body style="background:#88FDBD">
<br><h2><center>SEJA BEM-VINDO(A) {% if user.is_authenticated %}{{ user.first_name }}{% else %}usuário anônimo{% endif %}</h2>
<center>
<h3><a href="{% url 'users:logout' %}">Logout (Sair)</a>.</h3>
{% if user.is_authenticated %}
<br>
    <h1>{{playlist_name}}</h1>
    <ul>
    {% for track in tracks %}
        <li>{{track|get_item:name}} - {{track|get_artist_name}}</li>
    {% endfor %}
</ul>
{% else %}
<p><a href="{% url 'users:register' %}">Registre-se</a>.</p>
<p><a href="{% url 'users:login' %}">Login</a>.</p>
{% endif %}

templates/users/register.html
<!-- Arquivo: templates/users/register.html -->
<h1><br><center> CADASTRO DE USUÁRIOS</h1>
<body style="background:#88FDBD">

<center>
<img src="https://cdn.theenemy.com.br/h0UEFooGg-qOzkfy7RhKRJsSl2c=/970x360/smart/media/uploads/conteudo/fotos/Spotify2.jpg" height="150" width="465" border="5"> 

<form role="form" class="form" method="POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-warning">CADASTRAR</button>
</form>

templates/users/search.html
<body style="background:#88FDBD">
<h2><center><br>SEJA BEM-VINDO(A)</h2>{% if user.is_authenticated %}{{ user.first_name }}{% else %}{% endif %}</p>
{% if user.is_authenticated %}
            <form  id="user_form" method="post" action="{% url 'users:search' %}">
                {% csrf_token %}
                <!-- Display the search form elements here -->
                <input type="text" size="50" name="query" value="" id="query" />
                <input type="submit" name="submit" value="Search" />
                <br />
            </form>
                {% for result in result_list %}

                        <h4>{{result|get_item:name}}</h4>

                {% endfor %}
{% else %}
<center>
<img src="https://img2.ibxk.com.br/2016/12/01/01123842236162.jpg?w=480&h=280&mode=crop" height="170" width="465" border="5">
<h3>
<h3>É NOVO(A) POR AQUI?</h4>
<img src="https://image.freepik.com/icones-gratis/baixar-ou-seta-apontando-para-baixo_318-33675.jpg" height="70" width="70" border="5">

<h3><a href="{% url 'users:register' %}">REGISTRE-SE</a></p>
<h3>JÁ É VETERANO(A)?</h4>
<img src="https://image.freepik.com/icones-gratis/baixar-ou-seta-apontando-para-baixo_318-33675.jpg" height="70" width="70" border="5">
<h3><a href="{% url 'users:login' %}">LOGIN</a></p>
{% endif %}